
server:
  port: 8088
  servlet:
    context-path: /note
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notebase?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456


